### ISSUE TITLE
layer-snap throws CalledProcessError: Command on snap install command

### ISSUE THREAD

**Issue by chrisheckler** [stub42/layer-snap#15]
```console unit-snap-db-redis-15: 16:56:46 ERROR unit.snap-db-redis/15.juju-log Hook error:
Traceback (most recent call last):
 File "/var/lib/juju/agents/unit-snap-db-redis-15/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 71, in main
   hookenv._run_atstart()
 File "/var/lib/juju/agents/unit-snap-db-redis-15/.venv/lib/python3.6/site-packages/charmhelpers/core/hookenv.py", line 1119, in _run_atstart
   callback(*args, **kwargs)
 File "/var/lib/juju/agents/unit-snap-db-redis-15/charm/reactive/snap.py", line 70, in install
   snap.install(snapname, **snap_opts)
 File "lib/charms/layer/snap.py", line 47, in install
   _install_local(res_path, **kw)
 File "lib/charms/layer/snap.py", line 222, in _install_local
   subprocess.check_call(cmd, universal_newlines=True)
 File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['snap', 'install', '--dangerous', '--classic', '--dangerous', '/var/lib/juju/agents/unit-snap-db-redis-15/resources/flask-gunicorn-nginx/flask.snap']' returned non-zero exit status 1.

**Comment by stub42** [comment]
There will be some output before the traceback that will be helpful (the output from the 'snap install' command, unfortunately poorly interleaved in the logs).

There are many reasons that the snap install might fail here, such as out of disk space or constraints being enforced by snapd, so I should catch this exception and alert or log the problem more clearly.

**Comment by chrisheckler** [comment]
Here is more of the output as requested.
https://paste.ubuntu.com/p/7V6b6DgNYs/

Hopefully this helps.

**Comment by stub42** [comment]
```
unit-snap-db-redis-36: 00:20:16 INFO unit.snap-db-redis/36.juju-log Installing /var/lib/juju/agents/unit-snap-db-redis-36/resources/flask-gunicorn-nginx/flask-gunicorn-nginx_0.1_amd64.snap from local resource
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install error: cannot perform the following tasks:
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install - Setup snap "core" (4917) security profiles (cannot setup udev for snap "core": cannot reload udev rules: exit status 2
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install udev output:
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install )
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install - Setup snap "core" (4917) security profiles (cannot reload udev rules: exit status 2
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install udev output:
unit-snap-db-redis-36: 00:20:46 DEBUG unit.snap-db-redis/36.install )
```

The machine, VM or container does not support snaps, and the snap command is failing to report this is a meaningful fashion. I don't think there is anything the snap layer can do here to make it work, and you will likely need to go to forums.snapcraft.io for diagnosis.

The snap-layer needs to put the unit into a blocked state if installation fails, rather than an error state. Perhaps the core snap should be attempted separately, first, allowing us to report 'snaps not supported' rather than 'unable to install snap foo'

**Comment by chrisheckler** [comment]
Thank you for the insight.

**Comment by stub42** [comment]
Reopening to track improvements to notification when snap install fails.

**Comment by AurelienLourot** [comment]
I think the logging of `snap install` failures has been implemented by https://code.launchpad.net/~fnordahl/layer-snap/+git/layer-snap/+merge/371125 meanwhile. So this issue can be closed?

**Comment by stub42** [comment]
Indeed.

For the 'install can raise a CalledProcessError' issue, it would be possible to add an option to layer.yaml that supresses the exception, and making use of layer:status we can safely set a WAITING or BLOCKED status instead. But that is better tracked in a separate issue or PR if people care.
